### ISSUE TITLE
Delete a Question from Quiz (which was activated, and responded)

### ISSUE THREAD

**Issue by irudym** [irudym/iloilo-core#1]
When delete a question in Quiz which already has been activated, Rails provides error

```
Started DELETE "/questions/32" for 127.0.0.1 at 2020-04-21 10:48:15 +0300
Processing by V1::QuestionsController#destroy as JSON
  Parameters: {"id"=>"32"}
  User Load (1.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 4 LIMIT 1
  ↳ app/auth/authorize_api_request.rb:20:in `user'
  Admin Load (0.5ms)  SELECT `admins`.* FROM `admins` WHERE `admins`.`user_id` = 4 LIMIT 1
  ↳ app/models/user.rb:11:in `is_admin?'
  Question Load (0.6ms)  SELECT `questions`.* FROM `questions` WHERE `questions`.`id` = 32 LIMIT 1
  ↳ app/controllers/v1/questions_controller.rb:45:in `set_question'
  Quiz Load (2.1ms)  SELECT `quizzes`.* FROM `quizzes` WHERE `quizzes`.`id` = 9 LIMIT 1
  ↳ app/controllers/v1/questions_controller.rb:48:in `set_question'
  Quiz Exists? (11.4ms)  SELECT 1 AS one FROM `quizzes` WHERE `quizzes`.`user_id` = 4 AND `quizzes`.`id` = 9 LIMIT 1
  ↳ app/controllers/v1/questions_controller.rb:48:in `set_question'
  Answer Load (0.3ms)  SELECT `answers`.* FROM `answers` WHERE `answers`.`question_id` = 32
  ↳ app/models/question.rb:17:in `destroy_with_answers'
   (0.2ms)  BEGIN
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
  Answer Destroy (1.5ms)  DELETE FROM `answers` WHERE `answers`.`id` = 85
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (2.1ms)  COMMIT
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (1.1ms)  BEGIN
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
  Answer Destroy (18.9ms)  DELETE FROM `answers` WHERE `answers`.`id` = 86
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (2.4ms)  COMMIT
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (0.1ms)  BEGIN
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
  Answer Destroy (1.0ms)  DELETE FROM `answers` WHERE `answers`.`id` = 87
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (1.9ms)  COMMIT
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (0.1ms)  BEGIN
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
  Answer Destroy (1.8ms)  DELETE FROM `answers` WHERE `answers`.`id` = 88
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (2.8ms)  COMMIT
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (0.1ms)  BEGIN
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
  Answer Destroy (2.0ms)  DELETE FROM `answers` WHERE `answers`.`id` = 89
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (1.3ms)  COMMIT
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (0.1ms)  BEGIN
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
  Answer Destroy (1.0ms)  DELETE FROM `answers` WHERE `answers`.`id` = 90
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (0.8ms)  COMMIT
  ↳ app/models/question.rb:18:in `block in destroy_with_answers'
   (0.1ms)  BEGIN
  ↳ app/models/question.rb:20:in `destroy_with_answers'
  Question Destroy (5.0ms)  DELETE FROM `questions` WHERE `questions`.`id` = 32
  ↳ app/models/question.rb:20:in `destroy_with_answers'
   (5.3ms)  ROLLBACK
  ↳ app/models/question.rb:20:in `destroy_with_answers'
Completed 500 Internal Server Error in 129ms (ActiveRecord: 65.6ms | Allocations: 16548)

ActiveRecord::InvalidForeignKey (Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`iloilo_development`.`quiz_responses`, CONSTRAINT `fk_rails_a4c735b3c3` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`))):
  
app/models/question.rb:20:in `destroy_with_answers'
app/controllers/v1/questions_controller.rb:38:in `destroy'
```
Probably QuizResponse keeps it

**Comment by irudym** [comment]
Possible solution is to not delete such answers (everything should be kept in sake of history), just clear question_id in related Quiz record

**Comment by irudym** [comment]
Need to make quiz_id in Question optional.
